sudo: false
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install responses
  - pip install coverage
  - pip install python-coveralls

script:
  - coverage run ./setup.py test

after_success:
  - coveralls
